# Generated by Django 3.0.7 on 2021-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subrubric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название'),
        ),
    ]
