# Generated by Django 3.0.7 on 2021-11-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_additionalimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FloatField(default=0, verbose_name='Описание'),
        ),
    ]
